import torch
import soundfile as sf
from nemo.collections.tts.models import FastPitchModel, HifiGanModel

print("Loading fine-tuned FastPitch...")
spec_generator = FastPitchModel.restore_from(
    "{output_dir}/fastpitch_finetuned.nemo"
).eval().cuda()

hifigan_path = "{output_dir}/hifigan_finetuned.nemo"
import os
if os.path.exists(hifigan_path):
    print("Loading fine-tuned HiFi-GAN...")
    vocoder = HifiGanModel.restore_from(hifigan_path).eval().cuda()
else:
    print("Loading pretrained HiFi-GAN (fine-tuned not found)...")
    vocoder = HifiGanModel.from_pretrained("{cfg.HG_PRETRAINED}").eval().cuda()

def synthesize(text, output_path="output.wav", pace=1.0):
    """Generate speech from text and save to wav file."""
    with torch.no_grad():
        tokens = spec_generator.parse(text)
        spectrogram = spec_generator.generate_spectrogram(tokens=tokens, pace=pace)
        audio = vocoder.convert_spectrogram_to_audio(spec=spectrogram)

    audio_np = audio.squeeze().cpu().numpy()
    sf.write(output_path, audio_np, 22050)
    print(f"Saved: {{output_path}} ({{len(audio_np)/22050:.1f}}s)")
    return audio_np

# --- Test sentences ---
test_sentences = [
    "A young dancer holds a pose in an open field",
    "Three men standing on grass by the water looking at something on a table",
    "A man shows off an old fashioned bill",
    "A young welldressed black man seated behind a drum set and smiling",
    "A person wearing glasses sits on a train as they read a book",
    "A little girl talking on a phone",
    "A girl climbs an inflatable wall over water",
    "A small girl smiling on the beach",
    "A woman in a pink shirt eating dip from a bread bowl",
    "A boy in black clothes is doing a cartwheel on the beach",
    "An old man in a long black coat stands on the street.",
    "A woman is taking a man 's blood pressure in a kitchen.",
    "Asian ladies serving food to what it looks to be an Asian restaurant.",
    "A boy standing beside several goats, with a group of men in the back.",
    "Two kids play soccer in a field.",
    "A man doing a one armed handstand in the grass.",
    "Construction workers in hard hats building a house.",
    "A girl in a yellow tank top jumping a blue hurdle with people in the background.",
    "Two infants are at play in the yard.",
    "At a rodeo a young boy is trying to coral a sheep inside the arena.",
    "There is a scientist looking through a microscope.",
    "A man in a brown shirt and blue shorts walking in Droney Park.",
    "Man presenting a powerpoint presentation for several people.",
    "A man is exercising while having two bottles of tea ready to drink.",
    "A small group of people are playing video game instruments in someone 's living room.",
    "Four men place cones into the back of a work truck",
    "Four people sit and listen to a woman in a blue scoop neck talk with two bystanders in the background",
    "Two dogs on the beach running into the water",
    "Several children are playing a basketball game on a basketball court",
    "A man in a green shirt scowls as he stands on a city street",
    "A man with a camera and another man with a baby stroller are standing in a fenced in area",
    "Two people in yellow vests rests in carts",
    "A brown dog runs through the grass holding something in its mouth",
    "Lady with a black outfit and headset in her ear is fixing coffee",
    "Ice skater taking a hit by another player",
    "A small child wearing winter clothes smiles while standing in the snow.",
    "Teen grinding a bench on a skateboard",
    "Large group of bikers racing in a competition.",
    "Young child playing in the sand, on a deserted beach.",
    "A man is working under a white vehicle while a child watches him.",
    "Two girls and a boy are getting ready to jump into a backyard pool.",
    "A tractor is driving in a field.",
    "A lady cooking a cake for her family.",
    "Add the tune to the Rage Radio playlist.",
    "An African American man is standing on a bridge wearing a pink shirt.",
    "People are crouched on the ground preparing something in a metal dish.",
    "A worker with face protection is using a machine.",
    "A young snowboarder catches some air on his black snowboard.",
    "A little girl with arms outstretched is posing at the beach.",
    "A woman walking in rain, with a black shirt on.",
    "One man smokes a cigarette in the presence of another man at night",
    "A Caucasian woman listens as an Asian man in camouflage explains something",
    "Two construction workers are working in front of a wall which has a bunch of names carved into it",
    "A crowd of local fishermen inspect their nets on the beach",
    "A group of men jumping for a ball",
    "Some people and vehicles on a crowded street.",
    "man sitting in a wild life scene playing with a polar bear.",
    "A dog and person doing an agility course.",
    "A boy in a blue shirt is mountain biking on a track and catching air.",
    "Two people sitting in front of and interesting building holding a clear glass bottle.",
    "A man sleeping on a bench in a subway station.",
    "Man and child walking along the beach in the water.",
    "A man with a brown bag walks in front of a gray wall.",
    "A young man is skateboarding on a ramp and is standing on one arm.",
    "A man wearing urban combat pants is walking down the street carrying a toolbox.",
    "A dog sits back on his hind legs and another dog stoops down.",
    "Teen does trick on skateboard while riding the rail.",
    "The elderly gather for a Christmas vigil.",
    "Two elderly women with gray hair engaging in conversation.",
    "A man in a jacket is standing on a bus.",
    "A man waiting for the bus in a war torn country",
    "A young boy is running a race",
    "A dog running through water with a white toy in its mouth",
    "A little boy in a suit holds the ring for a wedding",
    "A man plays a musical instrument",
    "Constructions workers work on a railroad.",
    "A small child standing on a white circle on a sidewalk.",
    "A baseball pitcher in a blue, white and gray uniform midpitch.",
    "Two children are sleeping while someone is fingering through a book of music.",
    "A mountain biker catching some after taking off a ramp on a trail.",
    "A tourist taking pictures.",
    "A woman wearing a costume is being lifted up on the shoulders of her dance partner.",
    "Man riding a bicycle down a road with clouds overhead.",
    "Chefs prepare food for patrons of a sushi restaurant.",
    "Girl on a street using a hula hoop, with three people in the background.",
    "What's the weather like at Nationaal park.",
    "Military personnel patrol an area",
    "A schizophrenic man paints a caricature of two men despite there being only one woman",
    "A male tennis player wearing a white headband misses an inbounds ball",
    "A man in a red jacket is using a machine on blocks of ice in front of several spectators",
    "A female artist sketching a portrait",
    "Two women are crossing a bridge over a narrow waterway.",
    "A woman is wearing a bright orange and brown shirt.",
    "Three men sitting in a room looking at their one motorbike and one pedal bike.",
    "A dog is on a leash by a tree",
    "A dog catching a flexable Frisbee in its mouth.",
    "A firefighter looks at another firefighter in the blurry distance.",
    "A woman with four children are eating ice cream cones.",
    "An old lady consulting a paperback book.",
    "A golfer wearing a striped red polo shirt and white pants watches his drive after swinging.",
    "Two men converse with each other in a furnished room.",
    "A bull bucks a man to the ground during a rodeo.",
    "A man in a red vest is standing in front of a microphone and holding a handsaw.",
    "Two dogs play with each other outside.",
    "A line of people wait outside of a building.",
    "Two men wearing white tshirts are working at a meat counter.",
    "Two women are smiling next to a microphone on a stage.",
    "A man walks over a small sign carrying his bicycle.",
    "A toddler bends over to scoop some dirt out of the ground with his little green shovel.",
    "a man in a harness climbing a rock wall",
    "There is a dog humping a young girl.",
    "The man in white is talking to the women by the bench.",
    "A construction worker with an orange hat on a pulley.",
    "A group of African women and children wearing brightly colored clothes.",
    "A man in a light colored tshirt and jeans looks very animated while a woman in a blue and white striped shirt and overalls is preparing food",
    "A woman wearing a gray coat looks through a Landscope at a nature center.",
    "Two men are working on a circular window by standing on chairs",
    "A boy plays outside after a rain shower.",
    "A girl in a pink shirt is standing on a chair and inspecting a drink machine.",
    "I water my plants everyday after sunset.",
    "A child pours syrup on a spinning device",
    "Man watching child in hallway.",
    "One child is pointing to the sky and another is trying to block the sun to look",
    "Multiple people working on a wooden structure.",
    "Two people are walking on a striped path.",
    "A man runs down a mountain.",
    "A woman with a crossbody black purse is walking near a stairway with silver railing.",
    "Pretty nice neck you've got there.",
    "A group of people protesting.",
    "The Paramedics are helping someone wearing black shorts who is on the ground.",
    "People are shopping at an Asian market.",
    "A man selling cotton candy during rush hour.",
    "A women 's sports squad performs some tricks, including lifting members high and tossing a ball.",
    "A girl with short black hair and a girl with long blondhair pose while ice skating.",
    "A woman touching a man s face on a wall after they took a break from riding motorcycles",
    "An attractive lady wearing a low cut dress holding a purse walking in a group of other women",
    "Here is a girl in boots walking with her backpack under an umbrella in the rain",
    "A group of college students sitting on a couch in a coffee shop discussing an exam they just took",
    "A man is standing on some rocks while waves lap around him",
    "Pack of sled dogs in the snow, one barking.",
    "a girl wearing pink bounces on a bed",
    "A red crosscountry vehicle driving through a puddle with people looking on.",
    "A man with a gray beard sitting outside on a plastic storage crate.",
    "Nurses are looking at various toys in the medical center.",
    "Shorthaired female bartender making a drink.",
    "A white dog with a loose leash is on a dirt road",
    "A parade of some sort is taking place.",
    "An older woman is walking on the street with assorted rags on.",
    "A man walking away from the camera pulls a threewheeled cart through a dark alley.",
    "What are the movie times for films close by",
    "Search for the video game The Book of Heroic Failures",
    "Why does the cat always rub against your leg right after you get out of the shower?",
    "Give me the schedule for animated movies at the nearest cinema",
    "Keep It Simple (The KISS principal).",
    "A woman with a small child in her lap reading a picture book.",
    "The girl is wearing a white shirt and red pants, and jumps through water.",
    "A group of individuals in front of computers look at the front of the room.",
    "A baby wearing all white swinging on a swing.",
    "Male figures in Tshirts carry lengths of construction material along the top of incomplete seated bleachers.",
    "A young man rides a yellow and black skateboard at the top of a ramp.",
    "man surfing on a wave in the ocean",
    "Row of plastic horses that form a childrens ride with one child riding.",
    "Firemen emerge from a subway station.",
    "A person about in the middle of throwing a green bowling ball down a bowling lane.",
    "Slightly overweight women in bikinis are playing on a beach.",
    "Two men wearing helmets on a motorcycle.",
    "Two woman stand on a street corner and talk to a third person",
    "A beautiful waterfall with two people walking on the road beside it.",
    "Two people are outside walking their dog.",
    "Two men sit on a couch and talk.",
    "A woman dressed nicely stands happily with her camera.",
    "A golden retriever walking through high grass.",
    "A man in a blue coat stands on the street near buses.",
    "A young woman in a polka dot shirt and glasses in front of some trees.",
    "A brunette photographer is kneeling down to take a photo.",
    "A woman wearing eyeglasses, sitting in front of the table while making jewelries.",
    "A classroom full of students with laptop computers.",
    "A woman in a denim jacket is carting off a wheelbarrow as two other women watch.",
    "a female throws a frisbee while another attempts to block her toss.",
    "A street band of males playing drums.",
    "Members of the Salvation Army are standing together as one holds an instrument.",
    "Group of girls in red school uniforms walking on a busy sidewalk.",
    "Two dogs walk in the snow, the larger dog has a fish in his mouth.",
    "Two ladies and a little girl in her pajamas opening gifts",
    "A man in a black tank top wearing a red plaid hat",
    "A man who appears to be buying vegetables.",
    "Two UFC fighters duke it out on the mat.",
    "Three darkhaired people stand near each other with large buildings in the background.",
    "A woman walks after two geese near the ocean.",
    "An older gentleman in a brown cap looking at a younger gentleman 's arm.",
    "The lake was nestled in the ring of mountains.",
    "A group of students are sitting outside on campus.",
    "A man and woman sitting in chairs next to a turquoise truck.",
    "A construction worker is working on a support beam on a building.",
    "Asian woman harvesting wheat.",
    "A shirtless guy lays in the sand with a cow.",
    "Two men clearing up wreckage.",
    "The woman with blondhair holds her sunglasses.",
    "A group of ten horse riders wearing equestrian helmets gallop across a large grassy field.",
    "Workers standing in a rice paddy.",
]

print("\\nGenerating test sentences...\\n")
for i, text in enumerate(test_sentences):
    synthesize(text, f"{output_dir}/test_{{i+1:02d}}.wav")

print("\\nAll test sentences generated!")
print(f"Check output files in: {output_dir}/")
